### ISSUE TITLE
IOError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by blackere** [playmusicdecrypter/playmusicdecrypter#5]
I had this error:

> Traceback (most recent call last):
>  File "/usr/local/bin/playmusicdecrypter", line 4, in <module>
>    playmusicdecrypter.main()
>  File "/usr/local/lib/python2.7/dist-packages/playmusicdecrypter.py", line 170, in main
>    decrypt_files(options.library, destination_dir, options.database)
>  File "/usr/local/lib/python2.7/dist-packages/playmusicdecrypter.py", line 139, in decrypt_files
>    decrypter.decrypt_all(outfile)
>  File "/usr/local/lib/python2.7/dist-packages/playmusicdecrypter.py", line 58, in decrypt_all
>    destination = open(outfile, "wb") if outfile else sys.stdout
> IOError: [Errno 36] File name too long: '/PATH/FILE/FILENAMEVERYVERYLONG.mp3'

I solved it by adding a check on the length of the file:

```
def get_outfile(self):
        """Returns output filename based on song informations"""
        filename = "{AlbumArtist} - {Album} - Disc {DiscNumber} - Track {TrackNumber:02d} - {Title}.mp3".format(**self.info)
    """Fix "IOError: [Errno 36] File name too long:"""
    if len(filename) >= 255:
        filename = filename[:251]+".mp3"
    """End Fix"""
        return re.sub(r'[<>:"/\\|?*]', " ", filename)
```

Thanks for your work

**Comment by playmusicdecrypter** [comment]
Version 2.0 now creates directories for artists and albums, so filenames shouldn't be too long again. I am closing it for now, if you still have problems in version 2.0, just tell me and I will merge this fix.
